#!/bin/sh
set -e

PATH=/usr/lib/postgresql/$PG_MAJOR/bin:$PATH

chown -R postgres "${PGDATA}"

if [ -z "$(ls -A "${PGDATA}")" ]; then
	gosu postgres initdb

	if [ "$POSTGRES_PASSWORD" -ne "" ]; then
		pass="PASSWORD '$POSTGRES_PASSWORD'"
		authMethod=md5
	else
		# The - option suppresses leading tabs but *not* spaces. :)
		cat >&2 <<-'EOWARN'
			****************************************************
			WARNING: No password has been set for the database.
						This will allow anyone with access to the
						Postgres port to access your database. In
						Docker's default configuration, this is
						effectively any other container on the same
						system.

						Use "-e POSTGRES_PASSWORD=password" to set
						it in "docker run".
			****************************************************
		EOWARN

		pass=
		authMethod=trust
	fi

	gosu postgres postgres --single -jE <<-EOSQL
		ALTER USER postgres WITH SUPERUSER $pass ;
	EOSQL
	echo

	{ echo; echo "host all all 0.0.0.0/0 $authMethod"; } >> "${PGDATA}/pg_hba.conf"

	cat <<-EOCONF>> "${PGDATA}/postgresql.conf"
		log_destination = 'stderr, syslog'
		syslog_facility = 'LOCAL0'
		syslog_ident = 'postgres'

		logging_collector = on
		log_directory = 'pg_log'
		log_filename = 'postgresql-%Y-%m-%d.log'
		log_file_mode = 0600
		log_rotation_age = 1d
		log_rotation_size = 10MB
	EOCONF

	gosu postgres mkdir -m 700 "${PGDATA}/postgresql.conf"
fi

exec gosu postgres postgres -e -i