#!/bin/sh
set -e

PATH=/usr/lib/postgresql/$POSTGRES_VERSION/bin:$PATH

chown -R postgres $PGDATA

BOOTSTRAPPED="$PGDATA/.bootstrapped"

if [ ! -e $BOOTSTRAPPED ]; then
	gosu postgres initdb

	gosu postgres postgres --single -jE <<-EOSQL
		ALTER USER postgres WITH SUPERUSER PASSWORD '$POSTGRES_PASSWORD';
	EOSQL
	echo

	{ echo; echo "host all all 0.0.0.0/0 md5"; } >> "$PGDATA/pg_hba.conf"

	cat <<-EOCONF >> "$PGDATA/postgresql.conf"
		log_destination = 'stderr, syslog'
		syslog_facility = 'LOCAL0'
		syslog_ident = 'postgres'

		logging_collector = on
		log_directory = 'pg_log'
		log_filename = 'postgresql-%Y-%m-%d.log'
		log_file_mode = 0600
		log_rotation_age = 1d
		log_rotation_size = 10MB
	EOCONF

	gosu postgres mkdir -m 700 "$PGDATA/pg_log"

	touch $BOOTSTRAPPED
fi

exec gosu postgres postgres -e -i